#!/bin/bash
#PBS -l nodes=1:ppn=1,vmem=16gb,walltime=01:00:00
#PBS -N bl.coreg

#SBATCH --ntasks-per-node=1
#SBATCH --mem=16G
#SBATCH --time=01:00:00

set -e
set -x

if [ -n "$FREESURFER_LICENSE" ]; then
    echo $FREESURFER_LICENSE > license.txt
elif [ -n "$FS_LICENSE" ] && [ -f "$FS_LICENSE" ]; then
    cp "$FS_LICENSE" license.txt
else
    echo "Please set FREESURFER_LICENSE or FS_LICENSE in resource environment" && exit 1
fi

unset QT_QPA_PLATFORM
xvfb-run -a singularity exec \
  --pwd `pwd` \
  -B `pwd`/license.txt:/usr/local/freesurfer/license.txt \
  docker://brainlife/mne-freesurfer:7.3.2-1.2.1 \
  python3 main.py
