#!/bin/bash
#PBS -l nodes=1:ppn=1,vmem=40gb,walltime=04:00:00
#PBS -N bl.coreg

#SBATCH --ntasks-per-node=1
#SBATCH --mem=20G
#SBATCH --time=04:00:00

set -e
set -x

if [ -n "$FREESURFER_LICENSE" ]; then
    echo $FREESURFER_LICENSE > license.txt
elif [ -n "$FS_LICENSE" ] && [ -f "$FS_LICENSE" ]; then
    cp "$FS_LICENSE" license.txt
else
    echo "Please set FREESURFER_LICENSE or FS_LICENSE in resource environment" && exit 1
fi

singularity exec \
  -B `pwd`/license.txt:/opt/freesurfer/license.txt \
  docker://aunnikri642/app-freesurfer-mne-source-recon \
  python3 main.py
